apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  template:
    metadata:
      annotations:
        dapr.io/config: "featureconfig"
  metadata:
  - name: connectionString
    value: "amqp://guest:guest@localhost:5672"
  - name: durable
    value: "false"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
  - name: enableDeadLetter
    value: "true"
  # - name: autoAck
  #   value: "false"
  # - name: requeueInFailure
  #   value: "true"
